channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=25.0.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==1.24.4
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
